name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "secure-eyrie-29619"
          heroku_email: "kaluanbentes@gmail.com"
